import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.util.Enumeration;

import javax.swing.JFrame;

import org.omg.PortableInterceptor.ServerIdHelper;

class Server
{
    static Server serverObj;
    static Socket client; // socket for client
    static String serverIpAddress;
    static int serverSessionId; // sessionID auto - generated by the server
    Server()
    {
        serverObj=this;
        Enumeration e = null;
        try {
            e = NetworkInterface.getNetworkInterfaces();
        } catch (SocketException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        /* extracting the server ip address */
        NetworkInterface n = (NetworkInterface) e.nextElement();
        Enumeration ee = n.getInetAddresses();
        InetAddress i = (InetAddress) ee.nextElement();
        i = (InetAddress) ee.nextElement();
        serverIpAddress=""+i;
        serverSessionId=(int)(Math.random()*10000);
       
        System.out.println(serverIpAddress);
        System.out.println(serverSessionId);
       
    }
    
    static ServerSocket serverSocket;
    public static void main(String args[])
    {
    	/********************************************************************/
		/* for testing...
		 * creating various student objects 
		 * these students have audio and text doubts
		 */
    	
    	String filename= "Images/print.txt";
        FileWriter fw;
    try {
    fw = new FileWriter(filename,false);
    fw.write(String.format("%-20s%-20s%-20s%-20s%-10s", "MAC_ID", "USERNAME", "ROLL NO.","DOUBT TOPIC","DOUBT TEXT\n\n\n"));
      fw.close();
    } catch (IOException e1) {
    // TODO Auto-generated catch block
    e1.printStackTrace();
    } //the true will append the new data
       
     

    	new Student();
		ServerFrame sf=new ServerFrame();
		sf.setVisible(true);
		sf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	/********************************************************************/
    
		new Student("Lavish Kothari","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Rakshit","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Kavleen","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Nonu","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Shanky","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Mohit","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Ankit","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Rahul","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Lavish Kothari","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Rakshit Kothari","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Kavleen Kalra","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Jasmeet","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Sameer","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Shanky","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Nehal Mehta","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Kritik Jaroli","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Vatsal","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Ujjawal","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Priyank","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Pooja Kothari","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Deepak","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Saket","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Kush Kothari","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Love Kothari","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
    	new Student("Naveen","147","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Computer Graphics","","audio");
		
    	new Student("Lavish Kothari","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Rakshit Kothari","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Kavleen Kalra","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Nonujeet","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Love Kothari","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Kush Kothari","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Deepak","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Pooja","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("abc agrawal","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("xyz sharma","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("pqr sharma","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
    	new Student("Lavish","159","123.123.123","/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/a.jpg","Exception","please explain the null pointer exception","text");
	
		new Server();
		
		sf.ipLabel.setText("IP Address : "+serverIpAddress);
		sf.sessionIdLabel.setText("Session ID : "+serverSessionId);
		
        System.out.println(sf.ipAddress+ "  hi lavsih kothair " +sf.sessionId);
		try
        {
            serverSocket=new ServerSocket(5565);
        }
        catch(IOException io)
        {
            System.out.println("You got an exception : "+io);
        }
       
        try
        {
            while(true)
            {
                client=serverSocket.accept();
                System.out.println("a client connected");
                new LoginThread(serverObj);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}



class LoginThread implements Runnable
{
	DataInputStream dis;
	DataOutputStream dos;
	String username,roll,macid,doubtSubject,doubtText;
    File myFile = new File("s.txt");
    String clientIpAddress,clientSessionID;
    Socket client;
    Server server;
    int count=0;
    BufferedImage image;
    LoginThread(Server server)
    {
    	//System.out.println("Thread started");
        this.server=server;
        client=server.client;
        Thread thread=new Thread(this);
        thread.start();
    }

    public void receiveFile(File file)throws IOException
    {
    	FileOutputStream fileOut=new FileOutputStream(file);
    	byte[]buf=new byte[Short.MAX_VALUE];
    	int byteSent;
    	while((byteSent=dis.readShort())!=-1)
    	{
    		dis.readFully(buf,0,byteSent);
    		fileOut.write(buf,0,byteSent);
    		
    	}
    	fileOut.close();
    }
    
    @Override
    public void run()
    {
    	System.out.println("thread is running");
        while(true)
        {
            try
            {
            	/*
               	BufferedReader in = new BufferedReader(new InputStreamReader(client.getInputStream()));
               	PrintWriter out =  new PrintWriter(client.getOutputStream(),true);
               	*/
               	dis=new DataInputStream(client.getInputStream());
               	dos=new DataOutputStream(client.getOutputStream());
              
               	String test;
               	test=dis.readUTF();
               	if("USER".equals(test))
               	{
               		dos.writeUTF("1");
               		clientSessionID=dis.readUTF();
               		if(clientSessionID==null)
               			break;
	               	 if(server.serverSessionId==Integer.parseInt(clientSessionID))
	                 {
	                     dos.writeUTF("1");
	                  
	                     client.close();
	                     count=1;
	                     break;
	                 }
	               	 else
	               	 {
	               		 dos.writeUTF("0");
	               	 }
               	}
            	else{
                    //System.out.println("Audio doubt entered");
				    username=dis.readUTF();
				    roll=dis.readUTF();
				    macid=dis.readUTF();
				    doubtSubject=dis.readUTF();
				    doubtText=dis.readUTF();
				
				    System.out.println("username="+username);
				    System.out.println("roll="+roll);
				    System.out.println("macid="+macid);
				    System.out.println("doubtSubject="+doubtSubject);
				    System.out.println("doubtText="+doubtText);
				
				    
				    File outFile=new File("/home/lavish/Server_ClassRoom_Interaction/Server_ClassRoom_Interaction/Images/"+macid+".jpg");
				    
				    receiveFile(outFile);
				
				    System.out.println(outFile.getAbsolutePath());
				    new print_in_file(macid,username,roll,doubtSubject,doubtText);
				    new Student(username,roll,macid,outFile.getAbsolutePath(),doubtSubject,doubtText,"text");
				
				
				    dos.writeUTF("received");
				
				
				    client.close();
				    count=1;
				    break;
            	}
            }
            catch(Exception e)
            {
            	e.printStackTrace();
            }
            finally
            {
            	System.out.println("client ended");
                try {
				   client.close();
				   } catch (IOException e) {
				   // TODO Auto-generated catch block
				   e.printStackTrace();
				   }
                for(int i=0;i<Student.studentListText.size();i++)
            
                if(count==1)
                break;
            }
             
        }
    }
}